### ISSUE TITLE
Callback error

### ISSUE THREAD

**Issue by Ishikudeska** [rakesh37187/BBSaveEditor#2]
> Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "app.py", line 292, in _process_data_user
TypeError: cannot unpack non-iterable bool object

Spits this error out when trying to process game save. Using newest BB version

**Comment by rakesh37187** [comment]
I'll be honest. I never really got around finishing this up properly and was more of a program to develop some skills. If you want I could look into why that exception gets thrown. Any chance you could provide the save file?

**Comment by Ishikudeska** [comment]
Well actually its in the code:
` def _process_data_user(self):
        if self.file_location is None:
            messagebox.showwarning("User not loaded!", "No file selected")
        self.data, self.user = process_user(self.file_location)
        self._set_original_users_stats()

    def _process_data_gems(self):
        if self.file_location is None:
            messagebox.showwarning("File not loaded!", "No file selected")
        self.data, self.gems = process_gems(self.file_location)
        self._load_all_gems()`
Both of these call for 2 seperate pieces of data.
Which is what is causing the exception to be thrown

**Comment by DraconicOv** [comment]
From what I can tell, this happens when the file fails to start with "41000000000000"
(I've also had this error.) Some save files seem to simply not work, and this could be due to an issue with your code or with how PlayStation stores save files.
Possibly related: #3 
[Here](https://www.dropbox.com/scl/fo/3st7t1b3hpgyweim38ona/AFdY7sTSIuP3uBXaSToxUJk?rlkey=516oykjrjn0uqf1echks3mce8&st=18dw7n10&dl=0) are a few files with which you can reproduce the error, it was found in "User Editor" mode, although it may exist in the others as well.
