### ISSUE TITLE
 'NoneType' object has no attribute 'start' error when loading certain save files.

### ISSUE THREAD

**Issue by DraconicOv** [rakesh37187/BBSaveEditor#3]
I encountered the error
`Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "app.py", line 292, in _process_data_user
  File "process_save_file.py", line 15, in process_user
  File "process_save_file.py", line 54, in extract_user_info
AttributeError: 'NoneType' object has no attribute 'start'`
In attempting to load [this](https://www.dropbox.com/scl/fi/mdls4k1jfisk5o2x4h9ul/userdata0004?rlkey=tyuy0gc6efje61gt929lmblso&st=7am82jak&dl=0) save file. Interestingly, this didn't occur for all my save files, only some. It seems like the type of "found data" is None, most likely due to the Regex pattern not finding any matches. I'm not very knowledgeable about BB save editing, but I'm fairly knowledgeable about python and Regex, so I can quite possibly help out if you could tell me the intent behind the regex.

**Comment by moondrizzled** [comment]
did you ever fix this? im having the same issue

**Comment by DraconicOv** [comment]
> did you ever fix this? im having the same issue

mmmm, kinda not really? My acting assumption is that certain exported save files don't accurately represent save data, and are kinda just nothing-burgers that get exported with the rest of the saves. These nothing-burgers cause this issue-- one can "fix" this by simply avoiding these saves.

**Comment by moondrizzled** [comment]
> > did you ever fix this? im having the same issue
> 
> mmmm, kinda not really? My acting assumption is that certain exported save files don't accurately represent save data, and are kinda just nothing-burgers that get exported with the rest of the saves. These nothing-burgers cause this issue-- one can "fix" this by simply avoiding these saves.

ohh alright, thats a shame but it makes sense
